/* Rattibha Planner Dashboard — bilingual (EN / AR) layer.
   tr('English') → Arabic when window.__lang === 'ar'. Mirrors the app's lang.jsx. */

const AR = {
  // sidebar nav + chrome
  'Overview': 'نظرة عامة',
  'Open requests': 'الطلبات المفتوحة',
  'My Offers': 'عروضي',
  'Bookings': 'الحجوزات',
  'Calendar': 'التقويم',
  'Messages': 'الرسائل',
  'Earnings': 'الأرباح',
  'Profile': 'الملف التعريفي',
  'Pro': 'برو',
  'Boost your reach': 'وسّع انتشارك',
  'Feature your studio to 3× more clients.': 'روّج استوديوك لعملاء أكثر ٣ أضعاف.',
  'Upgrade': 'ترقية',
  'Search…': 'بحث…',
  // topbar titles
  'Welcome back, Lumière': 'مرحباً بعودتك، لوميير',
  'Here’s what’s happening with your studio today': 'إليك ما يجري في استوديوك اليوم',
  'Browse posted briefs and send quotes': 'تصفّح الطلبات وأرسل عروضك',
  'Quotes you’ve sent — track their status': 'العروض التي أرسلتها — تابع حالتها',
  'Manage your confirmed events': 'أدر مناسباتك المؤكّدة',
  'Your schedule at a glance': 'جدولك بلمحة',
  'Chat with your clients': 'تواصل مع عملائك',
  'Track revenue, balance and payouts': 'تابع الإيرادات والرصيد والمدفوعات',
  'How clients see you on Rattibha': 'كيف يراك العملاء على رتّبها',
  'Update your profile, images & services': 'حدّث ملفك وصورك وخدماتك',
  'Agreement progress with your client': 'تقدّم الاتفاقية مع عميلك',
  // overview KPIs
  'New leads': 'طلبات جديدة',
  'Active bookings': 'حجوزات نشطة',
  'Revenue (Mar)': 'الإيرادات (مارس)',
  'Avg. rating': 'متوسط التقييم',
  '+2 today': '+٢ اليوم',
  '+3 this month': '+٣ هذا الشهر',
  '168 reviews': '١٦٨ تقييماً',
  'Revenue': 'الإيرادات',
  'Last 7 months': 'آخر ٧ أشهر',
  'Recent activity': 'النشاط الأخير',
  'New open requests': 'طلبات مفتوحة جديدة',
  'Upcoming events': 'المناسبات القادمة',
  'View all →': 'عرض الكل ←',
  '+18%': '+١٨٪',
  'guests': 'ضيف',
  // KPI deltas already include +2 today / +3 this month / 168 reviews above
  // event categories
  'Wedding': 'زفاف', 'Engagement': 'خطوبة', 'Birthday': 'عيد ميلاد', 'Corporate': 'شركات', 'Gala': 'حفل كبير', 'Graduation': 'تخرّج',
  // booking stages
  'Planning': 'التخطيط', 'Design': 'التصميم', 'Final walkthrough': 'المعاينة النهائية', 'Awaiting deposit': 'بانتظار العربون',
  // activity feed
  'New lead from Noura Al-Qahtani': 'طلب جديد من نورة القحطاني',
  'Wedding · 220 guests': 'زفاف · ٢٢٠ ضيف',
  'Booking confirmed — Aisha & Omar': 'تأكّد الحجز — عائشة وعمر',
  'Deposit SAR 4,800 received': 'تم استلام عربون ٤٬٨٠٠ ريال',
  'New 5-star review from Mona K.': 'تقييم ٥ نجوم جديد من منى ك.',
  '"Magical birthday, flawless execution"': '«عيد ميلاد ساحر وتنفيذ متقن»',
  'Orbit Co. sent a message': 'أرسلت شركة أوربت رسالة',
  '"Can we add a second stage screen?"': '«هل يمكن إضافة شاشة ثانية للمسرح؟»',
  // common
  'Send quote': 'أرسل عرضاً',
  'View deal': 'عرض الصفقة',
  'Track deal': 'تابع الصفقة',
  'Re-quote': 'أعد التسعير',
  'Message': 'رسالة',
  'Message client': 'راسل العميل',
  'All': 'الكل',
  'Pending': 'قيد الانتظار',
  'Client viewed': 'شاهده العميل',
  'Accepted': 'مقبول',
  'Declined': 'مرفوض',
  'Your quote': 'عرضك',
  'Open': 'مفتوح',
  'Matched to your studio': 'مطابقة لاستوديوك',
  'Showing requests in': 'عرض الطلبات في',
  'you receive leads from clients in your city': 'تصلك الطلبات من العملاء في مدينتك',
  'All KSA': 'كل السعودية',
  // status / pipeline
  'Confirmed': 'مؤكّد',
  'In review': 'قيد المراجعة',
  'Awaiting your signature': 'بانتظار توقيعك',
  'Countersign': 'وقّع المقابل',
  'Countersign now': 'وقّع الآن',
  // bookings table
  'Client': 'العميل',
  'Event': 'المناسبة',
  'Date': 'التاريخ',
  'Status': 'الحالة',
  'Value': 'القيمة',
  // earnings
  'Available balance': 'الرصيد المتاح',
  'Withdraw': 'سحب',
  'This month': 'هذا الشهر',
  'Pending payout': 'مدفوعات معلّقة',
  'Total earned': 'إجمالي الأرباح',
  // profile / storefront
  'Edit': 'تعديل',
  'Manage': 'إدارة',
  'Services': 'الخدمات',
  'Portfolio': 'معرض الأعمال',
  'Edit storefront': 'تعديل المتجر',
  'Add service': 'أضف خدمة',
  'Save changes': 'حفظ التغييرات',
  'Cancel': 'إلغاء',
  // bookings / calendar / earnings
  'Total value': 'القيمة الإجمالية',
  'Payment': 'الدفع',
  'paid': 'مدفوع',
  'This month': 'هذا الشهر',
  'Add event / block date': 'أضف مناسبة / احجز تاريخاً',
  'Available balance': 'الرصيد المتاح',
  'Withdraw': 'سحب',
  'Pending payouts': 'مدفوعات معلّقة',
  'Transactions': 'المعاملات',
  'Type': 'النوع',
  'Amount': 'المبلغ',
  'Deposit': 'عربون',
  'Final': 'دفعة نهائية',
  'Paid': 'مدفوع',
  'Site visit': 'زيارة الموقع',
  'Birthday Bash': 'حفلة عيد ميلاد',
  // open requests board / submit proposal
  'Showing requests in': 'عرض الطلبات في',
  'you receive leads from clients in your city': 'تصلك الطلبات من العملاء في مدينتك',
  'All KSA': 'كل السعودية',
  'All Saudi Arabia': 'كل السعودية',
  'Send quote': 'أرسل عرضاً',
  'Ask a question': 'اطرح سؤالاً',
  'Posted': 'نُشر',
  'offers so far': 'عروض حتى الآن',
  'Client budget': 'ميزانية العميل',
  'Your proposal': 'عرضك',
  'Package': 'الباقة',
  'Message to client': 'رسالة إلى العميل',
  'Your quote': 'عرضك',
  'Platform fee (15%)': 'رسوم المنصة (١٥٪)',
  'You earn': 'أرباحك',
  'Send proposal': 'إرسال العرض',
  'Proposal sent': 'تم إرسال العرض',
  'The client will be notified of your quote.': 'سيُخطَر العميل بعرضك.',
  'No open requests here yet': 'لا توجد طلبات مفتوحة بعد',
  'No new briefs in your city right now. Toggle to All KSA to see more, or check back soon.': 'لا توجد طلبات جديدة في مدينتك الآن. بدّل إلى كل السعودية لرؤية المزيد، أو عُد قريباً.',
  'No open requests match this filter right now. Check back soon.': 'لا توجد طلبات مفتوحة تطابق هذا التصفية الآن. عُد قريباً.',
  'Refresh': 'تحديث',
  'Client request': 'طلب العميل',
  // deal timeline (planner side)
  'Request received': 'تم استلام الطلب',
  'Offer sent': 'تم إرسال العرض',
  'Client accepted': 'قبل العميل',
  'Countersign contract': 'وقّع الاتفاقية',
  'Deposit received': 'تم استلام العربون',
  'Event day': 'يوم المناسبة',
  'Deal': 'الصفقة',
  'Deal timeline': 'مسار الصفقة',
  'Now': 'الآن',
  'Action needed': 'إجراء مطلوب',
  'Event Services Agreement': 'اتفاقية خدمات المناسبات',
  'View': 'عرض',
  'Your countersignature required': 'توقيعك المقابل مطلوب',
  'Sign now': 'وقّع الآن',
  'Deal summary': 'ملخّص الصفقة',
  'Signature': 'سيقناتشر',
  'Event': 'المناسبة',
  'Total fee': 'إجمالي الرسوم',
  'Deposit (on signing)': 'العربون (عند التوقيع)',
  'Your earnings (after fee)': 'أرباحك (بعد الرسوم)',
  'One step away': 'تبقّى خطوة واحدة',
  'Countersign to confirm the booking': 'وقّع لتأكيد الحجز',
  'The deposit releases to your balance the moment you sign.': 'يُحوّل العربون إلى رصيدك فور توقيعك.',
  'Awaiting your signature': 'بانتظار توقيعك',
  'Message client': 'راسل العميل',
  'Service agreement': 'اتفاقية الخدمة',
  // messages + profile/storefront
  'Create booking': 'إنشاء حجز',
  'Write a reply…': 'اكتب رداً…',
  'Premium': 'مميّز',
  'Verified': 'موثّق',
  'Portfolio': 'معرض الأعمال',
  'From': 'يبدأ من',
  'Performance': 'الأداء',
  'Profile views': 'مشاهدات الملف',
  'Response rate': 'معدّل الاستجابة',
  'Avg. response': 'متوسط الرد',
  'Booking rate': 'معدّل الحجز',
  'Rating': 'التقييم',
  // edit storefront
  'Edit storefront': 'تعديل المتجر',
  'Profile': 'الملف التعريفي',
  'Replace cover': 'تغيير الغلاف',
  'Logo': 'الشعار',
  'Studio name': 'اسم الاستوديو',
  'Specialty': 'التخصّص',
  'City': 'المدينة',
  'Bio': 'نبذة',
  'Portfolio photos': 'صور معرض الأعمال',
  'Replace': 'تغيير',
  'Add': 'إضافة',
  'Event categories': 'فئات المناسبات',
  'Weddings': 'أعراس', 'Galas': 'حفلات كبرى', 'Engagements': 'خطوبات', 'Birthdays': 'أعياد ميلاد',
  'New service': 'خدمة جديدة',
  'Add image': 'أضف صورة',
  'Service name': 'اسم الخدمة',
  'From SAR': 'يبدأ من ريال',
  // lead detail + booking detail
  'Request': 'الطلب',
  'New lead': 'طلب جديد',
  'Event brief': 'موجز المناسبة',
  'Requirements': 'المتطلّبات',
  'Event type': 'نوع المناسبة',
  'Preferred date': 'التاريخ المفضّل',
  'Guest count': 'عدد الضيوف',
  'Location': 'الموقع',
  'Budget range': 'نطاق الميزانية',
  'Match score': 'درجة المطابقة',
  'fit for your studio': 'ملاءمة لاستوديوك',
  'Matches your category, city and budget tier. Respond fast to win it.': 'يطابق فئتك ومدينتك ومستوى ميزانيتك. بادر بالرد لتفوز به.',
  'Send offer now': 'أرسل العرض الآن',
  'Events booked': 'مناسبات محجوزة',
  'Verified client': 'عميل موثّق',
  'Yes': 'نعم',
  'Other planners': 'منظّمون آخرون',
  'Event value': 'قيمة المناسبة',
  'Booking confirmed': 'تأكّد الحجز',
  'Planning & design': 'التخطيط والتصميم',
  'Vendor coordination': 'تنسيق المورّدين',
  'Planning checklist': 'قائمة مهام التخطيط',
  '+ Add task': '+ أضف مهمة',
  'Share moodboard with client': 'مشاركة لوحة الإلهام مع العميل',
  'Confirm venue booking': 'تأكيد حجز القاعة',
  'Finalize catering menu': 'إنهاء قائمة الضيافة',
  'Send final invoice': 'إرسال الفاتورة النهائية',
  'Paid so far': 'المدفوع حتى الآن',
  'Balance': 'المتبقّي',
  'Total': 'الإجمالي',
  'Details': 'التفاصيل',
  'Event date': 'تاريخ المناسبة',
  'Stage': 'المرحلة',
  'Guests': 'الضيوف',
  'open': 'مفتوح',
  'offers': 'عروض',
  'Save changes': 'حفظ التغييرات',
  // My Offers / drawer
  'Quotes you’ve sent to clients · track their status here. New briefs to bid on live under': 'العروض التي أرسلتها للعملاء · تابع حالتها هنا. الطلبات الجديدة للمزايدة تظهر ضمن',
  'Viewed': 'تمت المشاهدة',
  'Sent': 'أُرسل',
  'Send an offer': 'إرسال عرض',
  'Choose a package': 'اختر باقة',
  'Your price (SAR)': 'سعرك (ريال)',
  'Message to client': 'رسالة إلى العميل',
  'Attach portfolio / moodboard': 'أرفق معرض الأعمال / لوحة الإلهام',
  'Send offer': 'إرسال العرض',
  'Send quote': 'أرسل عرضاً',
};

// Arabic city names (shared with app)
const CITY_AR = {
  'All Saudi Arabia': 'كل السعودية', 'Riyadh': 'الرياض', 'Jeddah': 'جدة', 'Makkah': 'مكة المكرمة',
  'Madinah': 'المدينة المنورة', 'Dammam': 'الدمام', 'Khobar': 'الخبر', 'Dhahran': 'الظهران',
  'Taif': 'الطائف', 'Tabuk': 'تبوك', 'Abha': 'أبها', 'Al-Ahsa': 'الأحساء', 'Buraidah': 'بريدة', 'Yanbu': 'ينبع',
};

function tr(s) {
  if (typeof window !== 'undefined' && window.__lang === 'ar') return AR[s] || s;
  return s;
}
function trCity(c) { return (typeof window !== 'undefined' && window.__lang === 'ar' && CITY_AR[c]) || c; }
const MONTH_AR = { Jan: 'يناير', Feb: 'فبراير', Mar: 'مارس', Apr: 'أبريل', May: 'مايو', Jun: 'يونيو',
  Jul: 'يوليو', Aug: 'أغسطس', Sep: 'سبتمبر', Oct: 'أكتوبر', Nov: 'نوفمبر', Dec: 'ديسمبر',
  JAN: 'يناير', FEB: 'فبراير', MAR: 'مارس', APR: 'أبريل', MAY: 'مايو', JUN: 'يونيو',
  JUL: 'يوليو', AUG: 'أغسطس', SEP: 'سبتمبر', OCT: 'أكتوبر', NOV: 'نوفمبر', DEC: 'ديسمبر' };
const NUM_AR = { '0':'٠','1':'١','2':'٢','3':'٣','4':'٤','5':'٥','6':'٦','7':'٧','8':'٨','9':'٩' };
function trMonth(m) { return (typeof window !== 'undefined' && window.__lang === 'ar' && MONTH_AR[m]) || m; }
function trNum(s) { return (typeof window !== 'undefined' && window.__lang === 'ar') ? String(s).replace(/[0-9]/g, d => NUM_AR[d]) : s; }
// localize a date like "14 Mar 2026" or "02 May 2026"
function trDate(s) {
  if (typeof window === 'undefined' || window.__lang !== 'ar') return s;
  return String(s).replace(/[A-Za-z]{3}/g, w => MONTH_AR[w] || w).replace(/[0-9]/g, d => NUM_AR[d]);
}
const isAR = () => typeof window !== 'undefined' && window.__lang === 'ar';

Object.assign(window, { AR, CITY_AR, tr, trCity, trMonth, trNum, trDate, isAR });
